screen:
    width: 1920
    height: 1080
initial_location_id: 1
location_tree:
    1:
        - 22
    3:
        - 22
    4:
        - 14
        - 22
        - 15
        - 8
    5:
        - 15
    6:
        - 15
    7:
        - 8
    8:
        - 4
        - 7
        - 9
    9:
        - 8
        - 15
    10:
        - 15
    11:
        - 12
    12:
        - 11
        - 15
        - 13
    13:
        - 12
    14:
        - 4
        - 16
    15:
        - 12
        - 10
        - 9
        - 6
        - 5
    16:
        - 14
    22:
        - 4
        - 3
